services:
  db:
    image: postgres:latest
    volumes:
      - dbvol:/var/lib/postgresql
    env_file:
      - .env.docker
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bother"]
      interval: 5s
      timeout: 5s
      retries: 5
  webserv:
    stdin_open: true
    tty: true
    stop_signal: SIGTERM
    stop_grace_period: 5s
    build:
      context: .
      dockerfile: webserv.dockerfile
    ports:
      - "8020:80"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker
    volumes:
      - logs:/var/log/amivizor/
    restart: on-failure
    develop:
      watch:
        - path: ./backend/
          target: /backend
          action: sync+restart

volumes:
  dbvol:
  logs:
